export enum NotionPageOrRecord {
    VIEW_ID = "notion-page-or-record-view-id",
    TITLE = "Create Page or Record",
    CREATE = "Create",
    CREATE_ACTION = "create-page-or-record-action-id",
    CREATE_BLOCK = "create-page-or-record-block-id",
    CLOSE = "Close",
    CLOSE_ACTION = "close-page-or-record-action-id",
    CLOSE_BLOCK = "close-page-or-record-block-id",
    TITLE_PLACEHOLDER = "Enter Title of Page or Record",
    TITLE_LABEL = "Title *",
    TITLE_BLOCK = "title-page-or-record-block-id",
    TITLE_ACTION = "title-page-or-record-action-id",
    CHANGE_DATABASE_TEXT = "Change Database",
    CHANGE_DATABASE_ACTION = "create-page-or-record-change-database-action-id",
    ADD_PROPERTY_ACTION = "add-property-create-page-or-record-action-id",
    ADD_PROPERTY_BLOCK = "add-property-create-page-or-record-action-id",
    ADD_PROPERTY_BUTTON_TEXT = "Add Property",
}
