export enum NotionPageOrRecord {
    VIEW_ID = "notion-page-or-record-view-id",
    TITLE = "Create Page or Record",
    CREATE = "Create",
    CREATE_ACTION = "create-page-or-record-action-id",
    CREATE_BLOCK = "create-page-or-record-block-id",
    CLOSE = "Close",
    CLOSE_ACTION = "close-page-or-record-action-id",
    CLOSE_BLOCK = "close-page-or-record-block-id",
    TITLE_PLACEHOLDER = "Enter Title of Page or Record",
    TITLE_LABEL = "Title *",
    TITLE_BLOCK = "title-page-or-record-block-id",
    TITLE_ACTION = "title-page-or-record-action-id",
    CHANGE_DATABASE_TEXT = "Change Database",
    CHANGE_DATABASE_ACTION = "create-page-or-record-change-database-action-id",
    PROPERTY_SELECTED_BLOCK_ELEMENT = "property-selected-element-create-page-or-record-block-id",
    OVERFLOW_MENU_ACTION = "create-notion-page-overflow-menu-action-id",
    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
}
