export enum PropertyTypeValue {
    TEXT = "rich_text",
    NUMBER = "number",
    SELECT = "select",
    MULTI_SELECT = "multi_select",
    DATE = "date",
    PEOPLE = "people",
    FILES = "files",
    CHECKBOX = "checkbox",
    URL = "url",
    EMAIL = "email",
    PHONE_NUMBER = "phone_number",
    FORMULA = "formula",
    RELATION = "relation",
    ROLLUP = "rollup",
    CREATED_TIME = "created_time",
    CREATED_BY = "created_by",
    LAST_EDITED_TIME = "last_edited_time",
    LAST_EDITED_BY = "last_edited_by",
}

export enum PropertyType {
    TEXT = "Text",
    NUMBER = "Number",
    SELECT = "Select",
    MULTI_SELECT = "Multi Select",
    DATE = "Date",
    PEOPLE = "People",
    FILES = "Files",
    CHECKBOX = "Checkbox",
    URL = "URL",
    EMAIL = "Email",
    PHONE_NUMBER = "Phone",
    FORMULA = "Formula",
    RELATION = "Relation",
    ROLLUP = "Rollup",
    CREATED_TIME = "Created time",
    CREATED_BY = "Created by",
    LAST_EDITED_TIME = "Last edited time",
    LAST_EDITED_BY = "Last edited by",
}
